apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
  service:test
spec:
  ports:
  - port: 31001
    nodePort: 31001
    targetPort: nodejs-port
    protocol: http
  selector:
    app: helloworld
  type: NodePort
